site_name: üî¨ pgwatch
site_description: pgwatch is a flexible PostgreSQL-specific monitoring solution
site_url: https://pgwat.ch/
use_directory_urls: false
copyright: Made by and for PostgreSQL lovers! üêò‚ù§Ô∏è
repo_name: pgwatch by Cybertec
repo_url: https://github.com/cybertec-postgresql/pgwatch
theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)" # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
  features:
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link

plugins:
  - search
  - tags  
  - glightbox
  # - minify:
  #     minify_html: true
 
nav:
  - Intro: 
    - Hello World!: index.md
    - Project Background: intro/project_background.md
    - Features: intro/features.md
  - Concepts:
    - Components: concept/components.md
    - Installation Options: concept/installation_options.md
    - Long Term Installations: concept/long_term_installations.md
    - Sizing Recommendations: howto/sizing_recommendations.md
    - Web UI: concept/web_ui.md
  - Tutorials:
    - Docker Installation: tutorial/docker_installation.md
    - Custom Installation: tutorial/custom_installation.md
    - Preparing Databases: tutorial/preparing_databases.md
    - Upgrading: tutorial/upgrading.md
  - How-To Guides:
    - Dashboarding and Alerting: howto/dashboarding_alerting.md
    - Using Managed Services: howto/using_managed_services.md
    - Bootstraping the Metrics Measurements Database (Sink): howto/metrics_db_bootstrap.md
  - Reference:
    - Advanced Features: reference/advanced_features.md
    - Metric Definitions: reference/metric_definitions.md
    - Technical Details: reference/technical_details.md
    - Security: reference/security.md
    - Kubernetes: reference/kubernetes.md
    - Environment Variables: reference/env_variables.md
  - Gallery: 
    - Dashboards: gallery/dashboards.md
    - Web UI: gallery/webui.md
  - Developer: 
    - Documentation: developer/godoc.md
    - Contributing: developer/contributing.md
    - Code of Conduct: developer/CODE_OF_CONDUCT.md
    - License: developer/LICENSE.md
    

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra:
  version:
    provider: mike