apiVersion: 1

datasources:
- name: pgwatch metrics (postgres)
  uid: pgwatch-metrics
  type: postgres
  url: postgres:5432
  access: proxy
  password: pgwatchadmin
  user: pgwatch
  database: pgwatch_metrics
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
     postgresVersion: 1500 
  version: 1
  editable: true
