include:
  - path: compose.timescaledb.yml
  - path: compose.pgpool.yml
  - path: compose.pgbouncer.yml  
  - path: compose.grafana.yml
  - path: compose.pgwatch.yml
  - path: compose.pgadmin.yml
  - path: compose.prometheus.yml
  - path: compose.patroni.yml  
